<?xml version="1.0" encoding="UTF-8"?><testrun name="TestRunner" project="apiTestRPE" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="tests.TestRunner" time="3.426">
    <testsuite name="Users" time="3.426">
      <testcase name="Nao deve cadastrar usuarios sem informar nome" classname="Users" time="3.426">
        <failure>java.lang.AssertionError: expected:&lt;422&gt; but was:&lt;201&gt;&#13;
	at org.junit.Assert.fail(Assert.java:89)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:835)&#13;
	at org.junit.Assert.assertEquals(Assert.java:647)&#13;
	at org.junit.Assert.assertEquals(Assert.java:633)&#13;
	at steps.UsersSteps.deve_retornar_erro_de_nome_invalido(UsersSteps.java:73)&#13;
	at âœ½.deve retornar erro de nome invalido(file:///C:/Users/rafae/Desktop/Tecnologia/Automacao2/ApiTestRPE/apiTestRPE/src/test/resources/features/Users.feature:14)&#13;
&#13;
</failure>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
