<?xml version="1.0" encoding="UTF-8"?><testrun name="TestRunner" project="apiTestRPE" tests="3" started="3" failures="1" errors="0" ignored="0">
  <testsuite name="tests.TestRunner" time="5.614">
    <testsuite name="Users" time="5.614">
      <testcase name="Deve cadastrar usuarios com sucesso preenchendo as informacoes corretamente" classname="Users" time="3.828"/>
      <testcase name="Nao deve cadastrar usuarios sem informar nome" classname="Users" time="0.865">
        <failure>java.lang.AssertionError: expected:&lt;422&gt; but was:&lt;201&gt;&#13;
	at org.junit.Assert.fail(Assert.java:89)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:835)&#13;
	at org.junit.Assert.assertEquals(Assert.java:647)&#13;
	at org.junit.Assert.assertEquals(Assert.java:633)&#13;
	at steps.users.UsersSteps.deve_retornar_erro_de_nome_invalido(UsersSteps.java:73)&#13;
	at âœ½.deve retornar erro de nome invalido(file:///C:/Users/rafae/Desktop/Tecnologia/Automacao2/ApiTestRPE/apiTestRPE/src/test/resources/features/users/Users.feature:14)&#13;
&#13;
</failure>
      </testcase>
      <testcase name="Deve listar usuarios com sucesso" classname="Users" time="0.92"/>
    </testsuite>
  </testsuite>
</testrun>
